### DISCUSSION TITLE
ESM + CJS deps build errors

### DISCUSSION THREAD

**Discussion by alexcroox** [floydspace/serverless-esbuild#329] [Q&A]
Running:

`serverless package --stage development`

```
service: exchange-api
frameworkVersion: '3'

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs16.x
  timeout: 15
  tracing:
    lambda: true

plugins:
  - serverless-plugin-monorepo
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-prune-plugin
  - serverless-offline

package:
  patterns:
    - '!package-lock.json'
    - '!.env.*'
    - '!db/**'

custom:
  esbuild:
    platform: neutral
    bundle: true
    minify: false
    target: node16
  prune:
    automatic: true
    number: 3

functions:
  api:
    handler: src/lambda.handler
    url:
      cors: true
```

I get the following errors when my deps use node built in libs like path/url/fs etc

![Screenshot 2022-06-30 at 22 20 11](https://user-images.githubusercontent.com/1065835/176780266-2e4a061f-8a84-45c3-9c7c-16a31841bd4a.png)

Should I be manually installing these build in node modules in order to use ESM src mixed with CJS deps?
