### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by ipauler** [floydspace/serverless-esbuild#102]
Is there a way to include graphql files?
There's a esbuild-graphql plugin, but i'm not sure how to use it here

**Comment by floydspace** [comment]
Hi @ipauler you can use `esbuild` built-in `text` loader like this:
```
custom:
  esbuild:
    loader:
      .graphql: text
```
so it will bundle .graphql files

**Comment by floydspace** [comment]
We have an open issue https://github.com/floydspace/serverless-esbuild/issues/97 about plugin support, so it's kind of related. We need to make sure that https://github.com/luckycatfactory/esbuild-graphql-loader is usable with `serverless-esbuild`

**Comment by ipauler** [comment]
Got it, thanks.
For now got it solved by using 
```
package:
  individually: true  
  include:
    - src/**/graphql/schema.graphql
  ```
