### ISSUE TITLE
package.patterns seems to be ignored

### ISSUE THREAD

**Issue by kabo** [floydspace/serverless-esbuild#110]
The README says

> All files from package/include will be included in the final build file. See [Exclude/Include](https://serverless.com/framework/docs/providers/aws/guide/packaging#exclude--include)

But package.include/exclude has been deprecated and replaced by package.patterns.

However, if I do something like

```yaml
  myFn:
    package:
      patterns:
        - resources/cert.cnf
```

that file is not included in the zip.

If I do

```yaml
  myFn:
    package:
      patterns:
        - '!**'
```

that doesn't have any effect either. It seems to just be ignored.
