### ISSUE TITLE
Unable to pass option to npm install

### ISSUE THREAD

**Issue by exoego** [floydspace/serverless-esbuild#115]
Hello.

On NPM v7+, my package.json requires `npm install  --legacy-peer-deps` command to be executed, instead of plain `npm install`.
However, it seems that serverless-esbuild currently does not support passing options to `npm install`:
https://github.com/floydspace/serverless-esbuild/blob/753e4aede6e826adc77cf82847520f1f84f9bef8/src/packagers/npm.ts#L104-L109

It would be helpful if there is an option to passing arguments to `npm install` something like:

```yaml
custom:
  esbuild:
    installOption:
      args: "--legacy-peer-deps" # maybe too primitive?

```

## Environment info

* npm: v7.6.3
* Node.js: v14.16.0

## Reproduction

1. Setup files like below.
2. `npm install --legacy-peer-deps`
3. `sls deploy`

Files
* serverless.yml
* package.json
* src
    * index.ts

serverless.yml
```yaml
service: issue-repro

plugins:
  - serverless-esbuild

custom:
  esbuild:
    external:
      - 'aws-appsync'
      - 'graphql-tag'

provider:
  name: aws
  region: ap-northeast-1
  runtime: nodejs14.x
  memorySize: 256
  versionFunctions: false
  lambdaHashingVersion: 20201221

functions:
  helloworld:
    handler: src/index.helloworld
    events: []
```

package.json
```json
{
  "name": "issue-repro",
  "version": "0.1.0",
  "devDependencies": {
    "@types/aws-lambda": "^8.10.75",
    "@types/node": "^14.14.41",
    "serverless": "^2.35.0",
    "serverless-esbuild": "^1.10.2",
    "ts-node": "^9.1.1",
    "typescript": "~4.2.4"
  },
  "dependencies": {
    "aws-appsync": "^4.0.3",
    "graphql-tag": "^2.11.0"
  },
  "scripts": {}
}
```

index.ts
```typescript
import type {MSKHandler} from 'aws-lambda';

import gql from 'graphql-tag';
import AWSAppSyncClient from 'aws-appsync';

const appSyncClient = new AWSAppSyncClient({
    auth: {...},
    region: "...", 
    url: "..."
});

const helloworld: MSKHandler = async (event) => {
    const query = gql(`mutation Test($message: String!){
      create(message: $message){
        id
        message
      }
    }`);

    const params =  {
        "message": "TEST"
    }

    try {
        await appSyncClient.mutate({
            variables: params,
            mutation: query
        });
        console.log("Success.");
    } catch (err) {
        console.error(JSON.stringify(err));
        throw new Error("Mutation failed !!")
    }
};

export {
    helloworld
};
```
