### ISSUE TITLE
Stuck at `moveArtifactsToPackage` during package cmd and `Successfully published` on deploy

### ISSUE THREAD

**Issue by bkniffler** [floydspace/serverless-esbuild#124]
I'm using serverless 2.39.0, also tried 2.38.0. Both package and deploy commands get stuck at the end and fail to exit the process without any clear error. Outputs are below and are with verbose+debug enabled. 

Tried different configs, but it keeps on hanging on that moveToArtifactsToPackage step. Deploying still does work though, but the process will need to be cancelled with ctrl+c.

If I exchange `serverless-esbuild` with `serverless-bundler`, the process exits correctly.

Logs (package)
```
....
Serverless: Packaging service...
Serverless: Installing dependencies for custom CloudFormation resources...
Serverless: Invoke aws:package:finalize
Serverless: Invoke aws:common:moveArtifactsToPackage
```

Logs (deploy)
```
....
Serverless: Invoke aws:deploy:finalize
Serverless: Removing old service artifacts from S3...
Serverless: Publishing service to the Serverless Dashboard...
Serverless: Successfully published your service to the Serverless Dashboard: xxxx
```

Config
```
custom:
  esbuild:
    packager: npm
    bundle: true
    minify: false
    sourcemap: true
    target: node14
    watch:
      pattern: ['./index.ts', 'src/**/*.ts'] # default .
      ignore: ['.serverless/**/*', '.build'] # default ['.build', 'dist', 'node_modules']
```

Any idea what could be wrong?
