### ISSUE TITLE
Use provider.runtime to guess esbuild target

### ISSUE THREAD

**Issue by Mihailoff** [floydspace/serverless-esbuild#126]
A nice to have feature request.

Docs say 
> The default JavaScript syntax target is set to ES2017

Plugin could use `provider.runtime` to change the target accordingly

In my case I ended up with 
```
provider:
  runtime: nodejs14.x
  
custom:
  esbuild:
    target: es2020
```

And thank you for the super fast compiler!

**Comment by floydspace** [comment]
hi @Mihailoff, thanks for the request, it makes sense.
And all the kudos for the compiler goes to @evanw

**Comment by mattisdada** [comment]
Agreed this is a nice to have feature

One FYI, the `target` can actually be the Node version. Examples: 
```yaml
provider:
  runtime: nodejs14.x
  
custom:
  esbuild:
    target: node14
```

```yaml
provider:
  runtime: nodejs12.x
  
custom:
  esbuild:
    target: node12
```

Source: https://esbuild.github.io/api/#target

That way you don't need to worry about which es version is compatible with which node version, `esbuild` already has that specific information to make sure the right features are used.
