### ISSUE TITLE
Odd file duplication in zip artifact after version 1.10.0 with individual packaging

### ISSUE THREAD

**Issue by clawsl** [floydspace/serverless-esbuild#140]
Hi,

First of all, thank you for the great plugin. It speeds up deployments for me a lot.

Recently I ran into an issue odd issue after trying to upgrade to a later version of it. What happens it the following:

- Up to 1.10.0 the zip files in the .serverless folder are fine and just contain a single bundled file for each function as expected. 
_**Working zip example:**_
![working_zip](https://user-images.githubusercontent.com/78071043/121722833-bb117a00-cadd-11eb-99aa-4213a4c5c878.png)

- Starting with 1.10.1 the zips contain the original (unbundled) source file in addition to the bundled version. This seems to overwrite the bundled version during the cloud formation deployment for me.
_**Broken zip example:**_
![broken_zip](https://user-images.githubusercontent.com/78071043/121722866-c5cc0f00-cadd-11eb-9083-34e536881418.png)

**Configuration Info**

serverless.yaml 
```
package:
  individually: true

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-offline-direct-lambda
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation
  - serverless-pseudo-parameters

custom:
   esbuild:
     bundle: true
     minify: true
     packager: npm
     exclude: ['pg-native']
...
```

package.json 
```
"devDependencies": {
    "dotenv": "^8.2.0",
    "eslint": "6",
    "eslint-config-airbnb-base": "^14.0.0",
    "eslint-config-node": "^4.0.0",
    "eslint-config-prettier": "^6.10.0",
    "eslint-plugin-import": "^2.20.1",
    "eslint-plugin-node": "^10.0.0",
    "jest": "^24.9.0",
    "prettier": "^1.19.1",
    "serverless": "^2.46.0",
    "serverless-aws-documentation": "^1.1.0",
    "serverless-esbuild": "^1.10.0",
    "serverless-offline": "^6.8.0",
    "serverless-offline-direct-lambda": "0.0.1",
    "serverless-pseudo-parameters": "^2.5.0",
    "serverless-reqvalidator-plugin": "^1.0.3",
    "typescript": "^3.6.3"
  },
  "dependencies": {
    "aws-sdk": "^2.656.0",
    "node-fetch": "^2.6.0",
    "node-gyp": "^7.1.2",
    "pg": "^8.3.0",
    "pg-copy-streams": "^5.1.1",
    "pump": "^3.0.0",
    "request": "^2",
    "rxjs": "^6.5.5",
    "s3-download-stream": "^1.1.1",
    "winston": "https://gitlab.com/mm123/winston-kf/-/archive/3.2.2/winston-kf-3.2.2.tar.gz",
    "xmlhttprequest": "^1.8.0"
  }
```

I tried several later versions (1.10.1 - the 1st version with the issue, 1.10.8, 1.11.0, 1.12.0) and all of those have the same problem for me on esbuild@0.12.8. 

As soon as I downgrade to e.g. 1.10.0 or 1.9.1 via `npm npm i serverless-esbuild@1.10.0` and run `sls deploy` the issue is gone and all works as expected . 
After that I upgrade and deploy again and the file duplication reappears for me.

The esbuild version npm installs is consistent (0.12.8) and the only thing that varies is the serverless-esbuild version.
