### ISSUE TITLE
Option to skip packaging externals

### ISSUE THREAD

**Issue by samrith-s** [floydspace/serverless-esbuild#152]
Hey,

I have these options in my SLS config:
```yml
package:
    exclude:
        - 'cache-manager'
        - 'class-transformer'
        - 'class-validator'
        - '@nestjs/microservices'
        - '@nestjs/websockets'
    individually: true
custom:
    esbuild:
        bundle: true
        minify: true
        keepNames: true
        sourcemap: true
        external:
            - 'cache-manager'
            - 'class-transformer'
            - 'class-validator'
            - '@nestjs/microservices'
            - '@nestjs/websockets'
        plugins: 'esbuild.plugins.js'
```
However, once it bundles, it runs this:
```
Packing external modules: cache-manager, class-transformer, class-validator, @nestjs/microservices, @nestjs/websockets
```

I want to completely skip it as these packages are opt-in in NestJS. Is there any way to achieve it? I see from the code that this plugin packages externals. Is there any way to completely skip them?

**Comment by vamche** [comment]
Hello @samrith-s

You can list modules in the `external` section to not include them in the final artifact. 

> The package specified in the exclude option is passed to esbuild as external, but it is not included in the function bundle either. The default value for this option is ['aws-sdk'].

**Comment by samrith-s** [comment]
Hey @vamche ,

Thanks for your response. Afaik, I am already doing that. All the packages are listed in `custom.esbuild.external` and `package.exclude`, yet it packages them.

**Comment by vamche** [comment]
@samrith-s I was talking about the `serverless-esbuild` config. Could you please list them in `custom.esbuild.external` and try?

``` yaml
   custom:
    esbuild:
        bundle: true
        minify: true
        keepNames: true
        sourcemap: true
        external:
            - 'cache-manager'
            - 'class-transformer'
            - 'class-validator'
            - '@nestjs/microservices'
            - '@nestjs/websockets'
        exclude:
            - 'cache-manager'
            - 'class-transformer'
            - 'class-validator'
            - '@nestjs/microservices'
            - '@nestjs/websockets' 
        plugins: 'esbuild.plugins.js'


```
