### ISSUE TITLE
Package Individually + External Not Working

### ISSUE THREAD

**Issue by samchungy** [floydspace/serverless-esbuild#170]
When you set the plugin's Esbuild External functionality + Serverless' Package Individually capability I would expect that anything in External will get copied to each of the individually packaged zips however the individual function zips do not contain the external package.

```
  esbuild:
    external:
      - datadog-lambda-js
      
  package:
    individually: true
```
