### ISSUE TITLE
Serverless Offline path does not work with function level package pattern

### ISSUE THREAD

**Issue by samchungy** [floydspace/serverless-esbuild#195]
I am trying to run the following in a function in Serverless Offline

```
  const buffer = await readFile(
    __dirname + '/user-data.sh'
  );
```
but I will receive a file not found error.

```
package:
  individually: true

functions:
  start-server:
    package:
      patterns:
        - src/functions/start-server/luser-data.sh
 ```

But the file will be not found because it looks like serverless-esbuild will output the file to __only-serverless-dev-start-server/functions/start-server/user-data.sh folder instead of src/functions/start-server/user-data.sh

It looks like the package version works fine because it copies it over but it does not work with serverless-offline.

My work around is setting the top level package to include the file instead.
