### ISSUE TITLE
json and html is not bundle

### ISSUE THREAD

**Issue by jefftham** [floydspace/serverless-esbuild#209]
As node official website suggested to use fs module to load json file, but esbuild is not bundling the .json and .html extension.

https://nodejs.org/api/esm.html#esm_no_json_module_loading

```
// lambda throws "Runtime.UnhandledPromiseRejection: TypeError [ERR_INVALID_URL]: Invalid URL: ./jsonSchema.json"
import { readFile } from 'fs/promises';
const jsonSchema = JSON.parse(await readFile(new URL('./jsonSchema.json', import.meta.url)));
```

```
// this work correctly in lambda, but mocha throws TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".json"
import jsonSchema from './jsonSchema.json';
```

is there a way to use recommended way to bundle .json and .html files? i set the loader option but it is not working
```
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    keepNames: true
    loader:
      .html: text
      .json: text
```
