### ISSUE TITLE
ImportModuleError when executing lambdas

### ISSUE THREAD

**Issue by sahasd** [floydspace/serverless-esbuild#221]
When I add the es-build plugin to my serverless.yml file and deploy to AWS, I get the following issue when triggering a lambda called `InternalConfig`:
``` json
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 's_internalConfig'\nRequire stack:\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 's_internalConfig'",
        "Require stack:",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1072:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)",
        "    at Module.load (internal/modules/cjs/loader.js:937:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:778:12)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```
I get the same issue for all my lambdas deployed through serverless when using `serverless-esbuild`

For context, the InternalConfig lambda is defined in the `serverless.yml` file as follows:
``` YAML
  internalConfig:
    handler: './src/handlers/internal-config.main'
    events:
      - http:
          method: get
          path: /internal/config/{serviceName}
      - http:
          method: post
          path: /internal/config/{serviceName}
```

What's weird is this error does not exist if I swap out the `serverless-esbuild` plugin for another zero-config typescript support plugin like `serverless-plugin-typescript`.

Any ideas as to why this might be happening?
