### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by michaelknoch** [floydspace/serverless-esbuild#226]
would it be possible to publish the current master to npm? We would really like to consume one of the recent fixes https://github.com/floydspace/serverless-esbuild/commit/8e105a6ff5174d23adb1eb0e42606c63e1224d24. @gavynriebau @floydspace

**Comment by floydspace** [comment]
@michaelknoch the fix you're looking for is already released in [v1.21.1](https://github.com/floydspace/serverless-esbuild/releases/tag/v1.21.1). Ignore the failed pipeline, the publish was successful

**Comment by michaelknoch** [comment]
ok interesting @floydspace , it keep running into this error when trying to add extrArgs

> Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Compiling with esbuild...
 > /Users/michaelknoch/dev/flow/apollo-server/serverless/node_modules/esbuild/lib/main.js:220:12: error: Invalid option in build() call: "installExtraArgs"
    220 │       throw new Error(`Invalid option ${where}: "${key}"`);
        ╵             ^
    at checkForInvalidFlags (/Users/michaelknoch/dev/flow/apollo-server/serverless/node_modules/esbuild/lib/main.js:220:13)
    at flagsForBuildOptions (/Users/michaelknoch/dev/flow/apollo-server/serverless/node_modules/esbuild/lib/main.js:345:3)
    at Object.buildOrServe (/Users/michaelknoch/dev/flow/apollo-server/serverless/node_modules/esbuild/lib/main.js:934:15)
    at /Users/michaelknoch/dev/flow/apollo-server/serverless/node_modules/esbuild/lib/main.js:1521:17
    at new Promise (<anonymous>)
    at Object.build (/Users/michaelknoch/dev/flow/apollo-server/serverless/node_modules/esbuild/lib/main.js:1520:14)
    at Object.build (/Users/michaelknoch/dev/flow/apollo-server/serverless/node_modules/esbuild/lib/main.js:1396:51)
    at EsbuildPlugin.<anonymous> (/Users/michaelknoch/dev/flow/apollo-server/serverless/node_modules/serverless-esbuild/dist/index.js:147:48)


```yml
# serverless.yml

...

plugins:
    - serverless-offline
    - serverless-esbuild

custom:
    esbuild:
        external:
            - "..."
        packager: "npm"
        packagePath: "../package.json"
        sourcemap: "inline"
        sourcesContent: false
        installExtraArgs:
            - "--legacy-peer-deps"

```
