### ISSUE TITLE
`ModuleNotFoundError` when locally invoking a python function

### ISSUE THREAD

**Issue by shichongrui** [floydspace/serverless-esbuild#228]
In a project with both node and python functions, when you run `serverless invoke local -f pythonFunction -d "{}"` you receive a `ModuleNotFoundError`. If you comment out the `serverless-esbuild` plugin in the `serverless.yml` file it works.

I have attached an archive to reproduce the issue.

[python-test.zip](https://github.com/floydspace/serverless-esbuild/files/7513000/python-test.zip)

Repro steps:
 - `npm install`
 - `sls invoke local -f hello -d "{}"`
 - This should complete successfully
 - `sls invoke local -f world -d "{}"` 
 - This will fail with the `ModuleNotFoundError`
 - Comment out the `serverless-esbuild` plugin
 - `sls invoke local -f world -d "{}"`
 - This should complete successfully

**Comment by samchungy** [comment]
Have you tried using Serverless package patterns to include the python handler?

**Comment by shichongrui** [comment]
@samchungy I'm not sure what package patterns you are referring to. Could you point me to some documentation on that?
Also just to make sure the issue is clearly articulated, my issue is with local invocation of a python function in a serverless project using serverless-esbuild, not with packaging.

**Comment by samchungy** [comment]
> my issue is with local invocation of a python function in a serverless project using serverless-esbuild, not with packaging.

Your issue is with packaging because that's why it is failing. Since we explicitly ignore Python handlers you have to handle that part of the packaging yourself. You can use Serverless patterns to achieve this yourself. https://www.serverless.com/framework/docs/providers/aws/guide/packaging#examples

https://github.com/floydspace/serverless-esbuild/issues/225#issuecomment-964850136 also gave you an example

**Comment by shichongrui** [comment]
Finally got some time to look into this again. I've tried the suggestion from https://github.com/floydspace/serverless-esbuild/issues/225#issuecomment-964850136 as well as the suggestions from the serverless docs and still am encountering the same issue and if I comment out the `serverless-esbuild` plugin, it works. I've included a zip file to hopefully be able to reproduce or tell me what I'm missing.

Here is my serverless.yml

```
service: hello-world
plugins:
  - serverless-esbuild
provider:
  name: aws
  runtime: nodejs14.x
package:
  individually: true
functions:
  hello:
    handler: index.handler
  world:
    handler: python.handler
    runtime: python3.8
    package:
      patterns:
        - '!**/*'
        - 'python.py'

```

[python-test.zip](https://github.com/floydspace/serverless-esbuild/files/7591868/python-test.zip)
