### ISSUE TITLE
Duplicate file builds with Lambdas using same handler file

### ISSUE THREAD

**Issue by deel77** [floydspace/serverless-esbuild#242]
I have been playing with `logLevel: info`  and have discovered that if you have multiple lambda functions defined using same root handler file, builder is executed multiple times (once for each lambda) which adds build time for many functions.

Example `serverless.yml`
```
package:
  individually: false

functions:
  function1:
    handler: src/handler.handleFunction1
    events:
     - http:
          method: get
          path: function1

  function2:
    handler: src/handler.handleFunction2
    events:
     - http:
          method: get
          path: function2
```

It produces logs
```
  .esbuild\.build\src\handler.js      1.1mb
  .esbuild\.build\src\handler.js.map  4.2mb

Done in 386ms

  .esbuild\.build\src\handler.js      1.1mb
  .esbuild\.build\src\handler.js.map  4.2mb

Done in 400ms
```

I have tried it and is using it with multiple function and it really adds time to build.

It would be great if it was possible to only build unique files.
