### ISSUE TITLE
Cannot keep class names when minifying

### ISSUE THREAD

**Issue by klindklind** [floydspace/serverless-esbuild#255]
Is there a way to do minified deployment package so that class names are preserved?

It seems that esbuild api supports keeping names https://esbuild.github.io/api/#keep-names but cannot figure out how to pass that argument to this serverless plugin?

I've tried following `serverless.yml` config:

```
...
  esbuild:
    bundle: true
    sourcemap: false
    minify: true
    installExtraArgs:
      - '--keep-names'
package:
  individually: true
...
```
With no luck 😢

**Comment by samchungy** [comment]
You should be able to simply add it to the `esbuild` options. 

eg.

```
  esbuild:
    'keep-names': true
```

**Comment by klindklind** [comment]
Thanks for the tip @samchungy !

That casing doesn't actually work and gives following error
```
Serverless: Compiling with concurrency: Infinity
✘ [ERROR] Invalid option in build() call: "keep-names"

    .../node_modules/esbuild/lib/main.js:261:12:
      261 │       throw new Error(`Invalid option ${where}: "${key}"`);
```

but if those kebab-cased options are transformed to camelCase, works. So following does what I want

```
  esbuild:
    bundle: true
    sourcemap: false
    minify: true
    keepNames: true
```

Maybe https://github.com/floydspace/serverless-esbuild#configure could give little bit more tips that one can use any esbuild api options (https://esbuild.github.io/api/) to configure the serverless plugin but when using kebab-cased options, remember to do the casing switch.

And by the way (forgot in the bug opener) versions used:

```
 "esbuild": "0.14.11"
 "serverless-esbuild": "1.23.3"
```

Thanks for the great plugin! Won't be missing Webpack 😄
