### ISSUE TITLE
Dependency Injection not working when using serverless-esbuild plugin

### ISSUE THREAD

**Issue by svetlasyrimis** [floydspace/serverless-esbuild#260]
Hello, 

I've encountered that weirdly dependency injection breaks(Nest.js project) when attempting to use `serverless-esbuild` in local environment. However when attempting to use `serverless-webpack` it's all working fine. 

serverless-offline@8.3.1
serverless-esbuild@1.23.3
serverless@2.72.2 
serverless-webpack@5.6.0 

```serverless.yaml
custom:
  serverless-offline:
    httpPort: 4000
    lambdaPort: 4001
  esbuild:
    bundle: true
    minify: false
    platform: 'node'
    external:
      - "cache-manager"
      - "class-transformer"
      - "class-validator"
      - "@nestjs/microservices"
      - "@nestjs/websockets/socket-module"
      - "fastify-swagger"
    watch:
      pattern: ['src/**/*.ts']
 ```

**Comment by floydspace** [comment]
Het @svetlasyrimis, thanks for raising it. Does it work in the deployed environment?
Could you also try set all nestjs packages as external

**Comment by svetlasyrimis** [comment]
Thanks for your prompt reply, will try that. 

Using custom esbuild script to deploy, not sls.

**Comment by vinicius91carvalho** [comment]
You can try @anatine/esbuild-decorators

There's an example here: https://docs.serverless-stack.com/constructs/Function

**Comment by svetlasyrimis** [comment]
Update: Using `esbuild-plugin-ts-decorators` and plugins option in serverless.yaml actually made it work. Thanks for the help @vinicius91carvalho :)

**Comment by Bnic3** [comment]
> Update: Using `esbuild-plugin-ts-decorators` and plugins option in serverless.yaml actually made it work. Thanks for the help @vinicius91carvalho :)

@svetlasyrimis   Am i missing something? how do you use esbuild-plugin-ts-decorators in the serverless.ts file

**Comment by senghuotlay** [comment]
This is what she meant by


```
serverless.yml

  esbuild:
    plugins: esbuild-plugins.js
    bundle: true
    minify: true
    sourcemap: true
    external:
      - 'class-transformer'
      - 'class-validator'
      - '@nestjs/microservices'
      - '@nestjs/websockets/socket-module'

      - 'cache-manager'
      - 'fastify-swagger'
      ```
      
      ```
      esbuild-plugins.js

/* eslint-disable @typescript-eslint/no-var-requires */
const { esbuildDecorators } = require('esbuild-plugin-typescript-decorators');

module.exports = () => {
  return [esbuildDecorators()];
};
```
