### ISSUE TITLE
Cannot use debug breakpoint tool on VSCode

### ISSUE THREAD

**Issue by sinh117801** [floydspace/serverless-esbuild#272]
When I config this code in `serverless.yml`, I cannot use debugger breakpoint on VSCode.
```
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    keepNames: true
```
