### ISSUE TITLE
Extra file (package.json) not included into final zips

### ISSUE THREAD

**Issue by doteric** [floydspace/serverless-esbuild#315]
**Describe the bug**
Extra files (package.json to be exact) are not included into the final zips.

**Versions (please complete the following information):**
 - OS: Mac
 - Serverless Framework Version: 3.18.2
 - Plugin Version: 1.30.0

**Additional context**
So basically I wanted to use esbuild with ESM (AWS supports this for a while already). I set the `type` inside package.json to `module` and everything else needed for this move, worked fine, but the problem I stumbled upon is that serverless-esbuild simply does not include the `package.json` into the zip even if it's added to the `package.patterns` like so below.

```
custom:
  esbuild:
    bundle: true
    minify: false
    packager: 'yarn'
    target: 'node16'
    keepOutputDirectory: true

package:
  individually: true
  excludeDevDependencies: true
  patterns:
    - 'package.json'
```

It looks like the `.esbuild` contains the the `package.json`, but the zips themselves don't.

Of course I could just name my files `.mjs` instead, but that isn't an ideal solution for me.

**Comment by floydspace** [comment]
hi @doteric , to be honest, not sure what is the reason we exclude, maybe because anyway we deliver bundled code and `package.json` used to be just unnecessary development artifacts, but feel free to test it locally with `patch-package` for instance and let as know, if you'd like raise a PR, keep in mind that we do not use root `package.json` for packaging dependencies, we generate one here https://github.com/floydspace/serverless-esbuild/blob/master/src/pack-externals.ts#L293, maybe it makes sense store this file, not the root one, but we also have to copy some necessary module meta located in root `package.json` you mentioned so your js files are treated correctly by nodejs.

**Comment by doteric** [comment]
@floydspace , but this package.json seems to be generated only if there are external modules specified, right? Anyway it seems to be a bit mixed up. For now I'll hold with the PR as I don't have much time, but I assume the goal would be to use the base package.json and replace it with the necessary params (dependencies for example) generated by the package.json from the pack-externals.

**Comment by floydspace** [comment]
@doteric yes, you're absolutely right, only external modules, here is the thing, other dependencies are bundled and you don't need them in generated package.json. so your assumption is correct, but could be vice versa, some of the params from base package.json would be copied to generated one, because you probably do not need `scripts` for instance nad other dev specific meta.

**Comment by mpaleo** [comment]
@doteric Lambda relies on the package file or the file extension, so you could do something like this in your serverless.yml:
```
esbuild:
  format: esm
  outExtension:
    .js: .mjs
```

Ref: https://docs.aws.amazon.com/lambda/latest/dg/nodejs-handler.html

**Comment by mpaleo** [comment]
BTW, getting the `package.json` deployed to Lambda is still really useful, because if you combine `outExtension` with `external`, it will fail because it doesn't find the original one.

```
esbuild:
  format: esm
  outExtension:
    .js: .mjs
  external:
    - typeorm
```
