### ISSUE TITLE
Package individually not bundling external sub deps

### ISSUE THREAD

**Issue by alexcroox** [floydspace/serverless-esbuild#355]
I wanted to use package `individually: true` in order to introduce a new function.

However, without adding an additional function yet, just enabling the option to test it would result in my function not working correctly.

Diving into the zip output comparisons of the 2 it seems that node_modules doesn't include all of the `external` sub dependancies:

```
plugins:
  - serverless-esbuild
  - serverless-dotenv-plugin
  - serverless-prune-plugin
  - serverless-offline

package:
  individually: true
  patterns:
    - '!package-lock.json'
    - '!.env.*'
    - '!db/**'

custom:
  esbuild:
    platform: node
    bundle: true
    external: ['knex', 'pg']

functions:
  api:
    handler: src/lambda.handler
    url: true
```

`individually: true` on the right, without on the left
![image](https://user-images.githubusercontent.com/1065835/182583159-12209719-b37e-413d-862d-02c2aff1e544.png)

Notice the missing extra `pg` deps for example from my `external` config

![image](https://user-images.githubusercontent.com/1065835/182583043-c70e1758-fb90-4374-8f1b-a4d3ff8efa74.png)

**Versions:**
 - OS: MacOS 12.4
 
"serverless": "3.21.0",
"serverless-dotenv-plugin": "4.0.2",
"serverless-esbuild": "1.32.5",
"serverless-offline": "9.1.3",
"serverless-prune-plugin": "2.0.1"

I'm using npm monorepo if it makes any difference
