### ISSUE TITLE
Something went wrong installing the "sharp" module with serverless offline and watch

### ISSUE THREAD

**Issue by efstathiosntonas** [floydspace/serverless-esbuild#370]
**Describe the bug**
When I run serverless offline and change something on a lambda function the next time the app tries to access an endpoint that uses `sharp` it throws this error: 

```bash
 Something went wrong installing the "sharp" module

  Module did not self-register: '/Users/stathis/WebstormProjects/xxxx/.esbuild/.build/node_modules/sharp/build/Release/sharp-darwin-x64.node'.

  Possible solutions:
  - Install with verbose logging and look for errors: "npm install --ignore-scripts=false --foreground-scripts --verbose sharp"
  - Install for the current darwin-x64 runtime: "npm install --platform=darwin --arch=x64 sharp"
  - Consult the installation documentation: https://sharp.pixelplumbing.com/install

```

**To Reproduce**
Steps to reproduce the behavior. If you have an example repository that would be even better:

1. run `serverless offline`
2. Change something inside a function
3. Let `serverless-esbuild` refresh/update
4. Try to access the lambda that uses`sharp`
5. Throws the error

**Please note that if I do not touch the lambda functions then it will never throw an error.**
I've monitored the `.esbuild/.build/node_modules/sharp/build/Release` folder and the `sharp-darwin-x64.node` is always there between code refreshes.

esbuild config on serverless.yaml:

```yaml
  esbuild:
    bundle: true
    external:
      - sharp
    minify: true
    sourcemap: true
    packager: yarn
    packagerOptions:
      scripts:
        - SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm_config_arch=x64 npm_config_platform=darwin yarn add sharp
    target: node16
    define: {}
    platform: node
    concurrency: 1
    watch:
      pattern: ["src/**/*.ts"] # match only typescript files in src directory
      ignore: ['.serverless/**/*', '.esbuild', 'node_modules']
```

If there's more information needed please let me know.

**Expected behavior**
I should not have to restart the `serverless offline` command everytime

**Versions (please complete the following information):**
 - OS: MacOS Monterey 12.5.1
 - Serverless Framework Version: `3.22.0`
 - Plugin Version: `1.32.8`
 - sharp version: `0.31.0`
 -  node version (nvm): `16.17.0`

**Comment by andidev** [comment]
I have the same/similar issue. It works in lambda environment but not with serverless offline.

and when I check the `node_modules/sharp/build/Release/sharp-darwin-arm64v8.node` is there 
but the issue is that it is not there in `.esbuild/.build/node_modules/sharp/build/Release/` folder. 
There I only find `sharp-linux-x64.node` which is the one specified to build in 
`serverless.yml`
```
  esbuild:
    packagerOptions:
      scripts:
        - rm -rf node_modules/sharp
        - SHARP_IGNORE_GLOBAL_LIBVIPS=1 npm install --arch=x64 --platform=linux --libc=glibc sharp
```

however I want this setting packagerOptions to only apply when running `sls deploy` and be ignored when running `sls offline`. 

I think this is the issue. How can this be accomplished?
