### ISSUE TITLE
Patterns work differently from node 14 to node 16

### ISSUE THREAD

**Issue by clementAC** [floydspace/serverless-esbuild#375]
**Describe the bug**
I have a configuration that works on node 14 and as soon as I upgrade to node 16, the configuration did not work. 
I'm trying to delete some file from @prisma deps as described in their [docs](https://www.prisma.io/docs/guides/deployment/deployment-guides/deploying-to-aws-lambda#package-pattern-in-serverlessyml).
The deletion works on .prisma and prisma directory but on node 16 I still have the content of @prisma/engines whereas it was not the case in node 14.

here is what I tried so far:

```yaml
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    packager: npm
    installExtraArgs: ['--production']
    exclude: ['aws-sdk', 'pg-native']
    external: ['pg']
    plugins: plugins.js
    keepOutputDirectory: true
.......
package:
  patterns:
    - '!node_modules/.prisma/**'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'

  individually: true

functions:
  graphql:
    timeout: 30
    memorySize: 512
    handler: src/lambdas/graphqlLambda.handler
    package:
      patterns:
        - 'node_modules/.prisma/client/libquery_engine-rhel-*'
        - 'node_modules/.prisma/client/*.js'
        - 'node_modules/.prisma/client/schema.prisma'
    events:
......
```
I'm only adding prisma to function that need it on function pattern level

**To Reproduce**

Quite complicated to reproduce as prisma need a db connection.

**Expected behavior**
To have patterns directives fully taken into account

**Versions :**

- OS: MacOS 12
- Serverless Framework Version: 3.22.0
- Plugin Version: 1.33.0
- esbuild-node-externals: 1.5.0

**Additional context**
Prisma 4
