### ISSUE TITLE
Using node lib that imports files with fs.readFileSync throws error

### ISSUE THREAD

**Issue by andidev** [floydspace/serverless-esbuild#384]
First I think this issue may maybe belong somewhere else. But I am not sure where and clueless in how to solve it.

I am trying to use node library [conekta-node](https://github.com/conekta/conekta-node) but when using it I get the following error:
```js
{
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/ben/Workspace/myserver/.esbuild/.build/cert/ca_bundle.crt'
}
```

and the reason is because these lines in code in node_modules
```js
const certPath = path.join(path.dirname(__dirname), '/cert/ca_bundle.crt')
...
ca: fs.readFileSync(certPath),
```
https://github.com/conekta/conekta-node/blob/master/lib/Requestor.js#L35

I tried
```yaml
custom:
  esbuild:
    external:
      - conekta
```

but it leads to other problems about other modules not being available.

I also tried 
```yaml
custom:
  esbuild:
    packagerOptions:
      scripts:
        - mkdir -p .esbuild/.build/cert
        - cp node_modules/conekta/cert/ca_bundle.crt .esbuild/.build/cert/ca_bundle.crt
```
but does not seem to copy ca_bundle.crt file

I searched everywhere for a solution but can't find any.

Any hints?
