### ISSUE TITLE
v1.35.0 break with serverless-offline

### ISSUE THREAD

**Issue by kennethwkz-mm** [floydspace/serverless-esbuild#415]
**Describe the bug**
Trying to start serverless offline but fail to start when using latest version 1.35.0

**To Reproduce**
Steps to reproduce the behavior. If you have an example repository that would be even better:

1. Run `sls offline start`

**Expected behavior**
Able to successfully run serverless offline in local environment

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.
```
28: 0x102a94eac v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
29: 0x102a943e0 v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
30: 0x102984914 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
31: 0x10276cd00 node::InternalCallbackScope::Close() [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
32: 0x10276cfc8 node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
33: 0x1027818ec node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node ./node_modules/serverless/bin/serverless offline --stage=stg --noAuth --noTimeout --localEnvironment --useInProcess --reloadHandler
Debugger attached.
Fetching Streams of [ Table : stg_ntf_MessageStatus ] in region ap-southeast-1
Fetched stream of [ Table : stg_ntf_MessageStatus ] => arn:aws:dynamodb:ap-southeast-1:XXXXXXXXXXXX:table/stg_ntf_MessageStatus/stream/2022-12-29T17:42:40.183Z
Fetching Streams of [ Table : stg_ntf_QueueBulkNotification ] in region ap-southeast-1
Fetched stream of [ Table : stg_ntf_QueueBulkNotification ] => arn:aws:dynamodb:ap-southeast-1:XXXXXXXXXXXX:table/stg_ntf_QueueBulkNotification/stream/2022-12-29T17:42:40.184Z


#
# Fatal error in , line 0
# Fatal JavaScript invalid size error 169220804
#
#
#
#FailureMessage Object: 0x16d68d378
 1: 0x10287f630 node::NodePlatform::GetStackTracePrinter()::$_3::__invoke() [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
 2: 0x1037931dc V8_Fatal(char const*, ...) [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
 3: 0x102ae3ed4 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
 4: 0x102c701bc v8::internal::(anonymous namespace)::ElementsAccessorBase<v8::internal::(anonymous namespace)::FastPackedObjectElementsAccessor, v8::internal::(anonymous namespace)::ElementsKindTraits<(v8::internal::ElementsKind)2> >::GrowCapacity(v8::internal::Handle<v8::internal::JSObject>, unsigned int) [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
 5: 0x102e70468 v8::internal::Runtime_GrowArrayElements(int, unsigned long*, v8::internal::Isolate*) [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
 6: 0x1031c904c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
 7: 0x13048f00c 
 8: 0x10315f000 Builtins_LoadIC_NoFeedback [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
 9: 0x103255604 Builtins_GetNamedPropertyHandler [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
10: 0x103154198 Builtins_InterpreterEntryTrampoline [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
11: 0x103154198 Builtins_InterpreterEntryTrampoline [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
12: 0x103185ef4 Builtins_AsyncFunctionAwaitResolveClosure [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
13: 0x1032146f8 Builtins_PromiseFulfillReactionJob [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
14: 0x103177c4c Builtins_RunMicrotasks [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
15: 0x1031523a4 Builtins_JSRunMicrotasksEntry [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
16: 0x102a94e7c v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
17: 0x102a9536c v8::internal::(anonymous namespace)::InvokeWithTryCatch(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
18: 0x102a95548 v8::internal::Execution::TryRunMicrotasks(v8::internal::Isolate*, v8::internal::MicrotaskQueue*, v8::internal::MaybeHandle<v8::internal::Object>*) [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
19: 0x102abbc18 v8::internal::MicrotaskQueue::RunMicrotasks(v8::internal::Isolate*) [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
20: 0x102abc4b0 v8::internal::MicrotaskQueue::PerformCheckpoint(v8::Isolate*) [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
21: 0x1029d920c v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
22: 0x1029d8d08 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
23: 0x1029d8534 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
24: 0x1031c918c Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
25: 0x1302aed48 
26: 0x1031524d0 Builtins_JSEntryTrampoline [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
27: 0x103152164 Builtins_JSEntry [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
34: 0x102826b34 node::fs::FSReqCallback::Resolve(v8::Local<v8::Value>) [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
35: 0x10282824c node::fs::AfterScanDir(uv_fs_s*) [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
36: 0x10281e7b0 node::MakeLibuvRequestCallback<uv_fs_s, void (*)(uv_fs_s*)>::Wrapper(uv_fs_s*) [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
37: 0x103130d28 uv__work_done [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
38: 0x1031344c4 uv__async_io [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
39: 0x103146210 uv__io_poll [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
40: 0x103134954 uv_run [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
41: 0x10276d6d4 node::SpinEventLoop(node::Environment*) [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
42: 0x10285d128 node::NodeMainInstance::Run() [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
43: 0x1027f0ec8 node::LoadSnapshotDataAndRun(node::SnapshotData const**, node::InitializationResult const*) [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
44: 0x1027f1190 node::Start(int, char**) [/Users/kennethwkz/.nvm/versions/node/v18.12.1/bin/node]
45: 0x10797108c 
```
**Versions (please complete the following information):**

- OS: Mac M1
- Serverless Framework Version: 3.26.0
- Plugin Version: 1.35.0

**Additional context**

**Comment by floydspace** [comment]
Hi @kennethwkz-mm thank you for raising the bug. Does the previous version work fine?

**Comment by kennethwkz-mm** [comment]
@floydspace yes 1.34.0 working fine

**Comment by floydspace** [comment]
@kennethwkz-mm I could not reproduce on one of the examples, unfortunately.
Could you maybe try one of the following:
- remove `node_modules` and reinstall them
- allocate more memory when running `sls offline`:
```
node --max-old-space-size=8192 node_modules/serverless/bin/serverless offline --stage=stg --noAuth --noTimeout --localEnvironment --useInProcess --reloadHandler
```
I simply googled the error you shared, and want to understand the cause of the issue, whether it's incorrect binaries or memory leaking.

**Comment by kennethwkz-mm** [comment]
@floydspace i tried no luck with that. I tested with 2 functions with package individually. 

This config works at 1.34.0 but when upgrade to 1.35.0 - it failed so I tested commented apiLambda & streamLambda package.patterns then will no more problem

```
package:
  individually: true
  patterns:
    - src/public/swagger.json
    - src/views/*
    - config/**

functions:
  apiLambda:
    handler: src/apiLambda.handler # required, handler set in AWS Lambda
    name: ${self:service}-${self:provider.stage}-api # optional, Deployed Lambda name
    description: ${self:service} API - ${self:provider.stage} # optional, Description to publish to AWS
    package:
      patterns:
        - src/public/swagger.json
        - package.json
        - src/views/*
        - node_modules/dynamoose-logger/**
        - node_modules/js-object-utilities/**
        - node_modules/uuid/**
    memorySize: 2048 # optional, in MB, default is 1024
    timeout: 29 # optional, in seconds, default is 6
    events:
      - httpApi:
          path: /api/swagger.json
          method: GET
      - httpApi:
          path: /api/healthcheck
          method: GET
      - httpApi:
          path: /api/webhook/sms
          method: POST
      - httpApi:
          path: /{proxy+}
          method: ANY
          authorizer:
            type: aws_iam
      - stream:
          type: dynamodb
          arn: ${fetchStreamARN(${self:provider.stage}_${self:service}_MessageStatus)}
          batchSize: 10
          parallelizationFactor: 10
          startingPosition: LATEST
          filterPatterns:
            - eventName: [INSERT]
              dynamodb:
                NewImage:
                  isSent:
                    N: ['0']
      - sns:
          arn:
            Fn::Join:
              - ':'
              - - 'arn:aws:sns'
                - Ref: 'AWS::Region'
                - Ref: 'AWS::AccountId'
                - 'SES'
          topicName: SES
    environment:
      INFOBIP_URL: ${env:INFOBIP_URL}
      INFOBIP_API_KEY: ${env:INFOBIP_API_KEY}
      INFOBIP_DEFAULT: ${env:INFOBIP_DEFAULT}
      EMAIL_SENDER: ${env:EMAIL_SENDER}
  streamLambda:
    handler: src/streamLambda.handler # required, handler set in AWS Lambda
    name: ${self:service}-${self:provider.stage}-stream # optional, Deployed Lambda name
    description: ${self:service} Stream - ${self:provider.stage} # optional, Description to publish to AWS
    package:
      patterns:
        - package.json
        - src/views/*
        - node_modules/dynamoose-logger/**
        - node_modules/js-object-utilities/**
        - node_modules/uuid/**
    memorySize: 4096 # optional, in MB, default is 1024
    timeout: 600 # optional, in seconds, default is 6
    events:
      - stream:
          type: dynamodb
          arn: ${fetchStreamARN(${self:provider.stage}_${self:service}_QueueBulkNotification)}
          batchSize: 1
          startingPosition: LATEST
          filterPatterns:
            - eventName: [INSERT]
              dynamodb:
                NewImage:
                  status:
                    S: ['processing']
            - eventName: [REMOVE]
              dynamodb:
                OldImage:
                  status:
                    S: ['pending']
    environment:
      INFOBIP_URL: ${env:INFOBIP_URL}
      INFOBIP_API_KEY: ${env:INFOBIP_API_KEY}
      INFOBIP_DEFAULT: ${env:INFOBIP_DEFAULT}
      EMAIL_SENDER: ${env:EMAIL_SENDER}
```
