### ISSUE TITLE
Endless compilation loop with serverless-offline

### ISSUE THREAD

**Issue by deanc** [floydspace/serverless-esbuild#463]
**Describe the bug**
When creating a syntax error when combined with `serverless-offline` with `--reloadHandler` flag we are experiencing incredibly high CPU and memory usage. Screenshot attached. The error log you see at the bottom of the issue happens several times a second in a loop.

![Screenshot 2023-05-10 at 13 33 35](https://github.com/floydspace/serverless-esbuild/assets/232423/4f53a18c-3f94-47ed-bcb8-be8ae26c0ffd)

- OS: MacOS (Latest)
- Plugins
```
"serverless": "^3.30.1",
"serverless-esbuild": "^1.44.0",
"serverless-offline": "^12.0.4",
```

Plugin configuration:
```
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    packager: 'yarn'
    exclude: ['aws-sdk']
    external: ['oracledb', 'tedious', 'pg', 'mysql', 'better-sqlite3', 'sqlite3', 'pg-query-stream']
```

![Screenshot 2023-05-10 at 13 32 18](https://github.com/floydspace/serverless-esbuild/assets/232423/e99b5995-19fa-489a-b61e-afb3b4a2d12b)
