### ISSUE TITLE
Get `runtime` from the function level

### ISSUE THREAD

**Issue by duncanista** [floydspace/serverless-esbuild#471]
## Problem

Currently, you can only build for runtimes at the provider level.
```yml
provider:
  name: aws
  region: sa-east-1
  runtime: nodejs18.x

functions:
  hello-world:
    handler: index.handler
```

If I want to build multiple functions with different runtimes, I have to create another `serverless.yml` file, which is not convenient.

## Proposed solution

I would like to build multiple functions with multiple runtimes.

```yml
provider:
  name: aws
  region: sa-east-1
  

functions:
  hello-world-node18:
    handler: index.handler
    runtime: nodejs18.x
   hello-world-node16:
    handler: index.handler
    runtime: nodejs16.x
```

Currently, this throws the following error:

```bash
Error:
AssertionError [ERR_ASSERTION]: not a supported runtime
    at new AssertionError (node:internal/assert/assertion_error:451:5)
```

## Alternatives considered
n/a

**Additional context**
- Latest version of `serverless`
- Latest version of `serverless-esbuild`
- LTS version of `node`.
