### ISSUE TITLE
Package individually doesn't optimise package size

### ISSUE THREAD

**Issue by PatrykMilewski** [floydspace/serverless-esbuild#79]
Hello!
This plugin works great, thank you for sharing it!

I wanted to test, if it works for our use case and I've found some problems.

We are using Yarn as package manager with workspaces enabled. In the stack that I'm testing, we are having 4 lambda functions. When I was using Webpack, each lambda had different package size, where the smallest was 1.5 MB and the biggest was 3 MB.

However when I was experimenting with this plugin, it looks like, package individually option doesn't work. The package size is 6 MB for each lambda, which equals the size of package, that is created when package individually is disabled. 

I was looking a little bit into the source code and it looks like, package individually option is handled by this plugin. Is this expected behaviour of esbuild? This is the config that I'm using:
```yaml
custom:
  esbuild:
    packager: yarn
    bundle: true
    minify: true
    sourcemap: true
    keepNames: true
```
Versions:
"serverless-esbuild": "1.5.1"
"serverless": "2.3.0"
Node.js v12.19.1

**Comment by floydspace** [comment]
Hey @PatrykMilewski, thank you for using the plugin.
Indeed, I was able to reproduce. It's handled, but halfway. so it does not work properly now.
Will work on the fix as soon as I have time.

**Comment by PatrykMilewski** [comment]
@floydspace Thanks! Could you share some more details? Maybe I could fix it myself and create a PR?

**Comment by floydspace** [comment]
@PatrykMilewski the issue is that serverless by default packs everything that is in the `this.serverless.config.servicePath` folder, I replace this folder to `.build` one as all compiled artifacts are stored there during the compilation. But seems like we have to prepare artifacts for each lambda manually, so compile, zip it, and provide the archive as lambda artifact. the implementation by `serverless-webpack` could work, see: [packageModules.js#L73](https://github.com/serverless-heaven/serverless-webpack/blob/38135e4443c7d7e8506010f0c3e411220abe6f24/lib/packageModules.js#L73)

**Comment by dashmug** [comment]
Thank you for this package @floydspace. I am experiencing the same problem with `v1.6.0`.

**Comment by dashmug** [comment]
My workaround is to use the `include`.

```yaml
functions:
  MyAPI:
    handler: src/core/my/handler.api
    package:
      include:
        - '!**'
        - 'src/core/my/**'
  TheirAPI:
    handler: src/core/their/handler.api
    package:
      include:
        - '!**'
        - 'src/core/their/**'
```

I don't have to do this with `serverless-webpack`.
