### ISSUE TITLE
package individually doesnt include node_modules and package.json

### ISSUE THREAD

**Issue by yeukfei02** [floydspace/serverless-esbuild#86]
Hi,

this is a nice lib.
but I try this lib with the serverless framework, I face some problem:

`serverless.yml`

```
package:
  individually: true
```

I didn't set anything in `custom`..inside the `.serverless` folder I don't see any `node_modules` + `package.json` file.
If I deploy this lambda func to aws, I guess will fail?
How can I make  `node_modules` + `package.json` file included in each lambda func zip?

Thanks!

**Comment by olup** [comment]
I'd say you have to declare externals if you want to have your modules added as externals modules to your zip. Otherwise, all the code is bundle as one js file, isn't it ?

It shouldn't fail, as long as you have no native dependencies in your modules - ie only javascript depencies that are bundable by esbuild

**Comment by yeukfei02** [comment]
@olup 

lets say I have 20+ restapi in `serverless.yml`
I check another issue say need to add `include` to each http event, so i need to manually add all `include` to those 20+ API...

because I was using `serverless-webpack` and this can help to add node_modules + package.json file to the individual package.
I am looking for `esbuild` to replace `webpack` because it is faster

**Comment by olup** [comment]
just use the external key of the config if you need, otherwise a single bundle should do. 

"I check another issue say need to add include to each http event, so i need to manually add all include to those 20+ API..." this is a workaround only needed if you want to have specific bundle size on each lambda. But it's a workaround, and may not be advisable in your own case. 

The bottom line is this package will work with individual pacakaging, but will not optimize the bundle size for each lambda, period. (or until the other ticket is addressed by maintainer or contributor)

**Comment by yeukfei02** [comment]
@olup 

thanks for the answer.
I think I will keep `serverless-webpack` first, but I will use `esbuild-loader` with it first.
for all the lambda func to do package individually.

**Comment by floydspace** [comment]
Hey @yeukfei02, we released the individually packaging fix in v1.8.0, could you please verify that it resolves your issue.

**Comment by yeukfei02** [comment]
@floydspace 

hey i just try in one of my project, I use with serverless framework and run `yarn run package`, this means `serverless package`..it cannot include `serverless_sdk` folder

```
yarn run package 
yarn run v1.22.10
$ serverless package
Serverless: Compiling with esbuild...
Serverless: Compiling completed.
Serverless: Zip function: k11-eshop-facebook-lambda-dev-eshopFacebook - 899.43 KB [75 ms]
 
  Error --------------------------------------------------
 
  Error: ENOENT: no such file or directory, scandir 'serverless_sdk'
```

thanks.

**Comment by olup** [comment]
hey @yeukfei02 . could you post here your `serverless.yml` file ?

**Comment by yeukfei02** [comment]
@olup 

`serverless.yml`

```
org: keysocapp
app: k11-eshop-facebook-lambda
service: k11-eshop-facebook-lambda

frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1
  apiName: k11-eshop-facebook-lambda-dev
  tracing:
    apiGateway: true
    lambda: true
  environment:
    NODE_ENV: development
    MY_AWS_ACCESS_KEY: ${param:MY_AWS_ACCESS_KEY}
    MY_AWS_SECRET_ACCESS_KEY: ${param:MY_AWS_SECRET_ACCESS_KEY}
    K11_ESHOP_FACEBOOK_LAMBDA_DATABASE_URL_DEV: ${param:K11_ESHOP_FACEBOOK_LAMBDA_DATABASE_URL_DEV}
    K11_ESHOP_FACEBOOK_LAMBDA_DATABASE_URL_PROD: ${param:K11_ESHOP_FACEBOOK_LAMBDA_DATABASE_URL_PROD}
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'xray:PutTraceSegments'
            - 'xray:PutTelemetryRecords'
          Resource:
            - '*'
        - Effect: 'Allow'
          Action:
            - 's3:PutObjectACL'
          Resource:
            - '*'
  apiGateway:
    shouldStartNameWithService: true
    description: K11 EShop Facebook Lambda Staging
  lambdaHashingVersion: 20201221
  vpc:
    securityGroupIds:
      - sg-0ba9e979cffe84d1c
    subnetIds:
      - subnet-0274899de33681214
  timeout: 30

package:
  individually: true

functions:
  eshopFacebook:
    handler: src/eshopFacebook/handler.eshopFacebook
    events:
      - http:
          path: /
          method: post
          cors: true
      - schedule: cron(0 15 * * ? *)
    timeout: 300

plugins:
  # - serverless-webpack
  - serverless-esbuild
  - serverless-prune-plugin
  # - serverless-plugin-typescript
  - serverless-offline
  # - serverless-plugin-split-stacks

custom:
  # webpack:
  #   webpackConfig: ./webpack.config.js
  #   includeModules: true
  #   packager: 'yarn'
  #   packagerOptions:
  #     scripts:
  #       - prisma generate
  prune:
    automatic: true
    number: 3
```

serverless version: `2.25.2`
